hybid.sdk/src/main/java/net/pubnative/lite/sdk/UserDataManager.java
This PR updates the privacy policy and vendor list urls for GDPR compliance
=> [MA-466] Update GDPR urls

hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/presenter/VastInterstitialPresenter.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/mrect/presenter/VastMRectPresenter.java
This PR forces the video player to mute before starting playing on VAST ads
=> Force video player mute before playing

hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/Ad.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/NativeAd.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/TrackingUrlModel.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/utils/text/StringUtils.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/views/PNBeaconWebView.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/visibility/TrackingManager.java, hybid.sdk/src/test/java/net/pubnative/lite/sdk/models/AdTestModel.java, hybid.sdk/src/test/java/net/pubnative/lite/sdk/models/NativeAdTest.java, hybid.sdk/src/test/java/net/pubnative/lite/sdk/visibility/ImpressionTrackerTest.java, hybid.sdk/src/test/java/net/pubnative/lite/sdk/visibility/VisibilityTrackerTest.java
- Create NativeAd class
- Fetch native assets from ad model
- Setup visibility tracking for native ads
- Tracking tests
=> [MA-447] Native asset fetching

hybid.demo/build.gradle, hybid.demo/src/main/AndroidManifest.xml, hybid.demo/src/main/java/net/pubnative/lite/demo/Constants.java, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/activities/hybid/HyBidNativeActivity.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidNativeFragment.kt, hybid.demo/src/main/res/layout/activity_hybid_native.xml, hybid.demo/src/main/res/layout/fragment_hybid.xml, hybid.demo/src/main/res/layout/fragment_hybid_native.xml, hybid.demo/src/main/res/values/strings.xml, hybid.sdk/src/main/java/net/pubnative/lite/sdk/api/NativeRequestManager.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/Ad.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/NativeAd.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/nativead/HyBidNativeAdRequest.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/views/PNBeaconWebView.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/visibility/TrackingManager.java
- Add license headers to new files
- Create HyBidNativeAdRequest to fetch native ads
- Prepare NativeAd to provide all resources needed to render native ads
=> [MA-448] Native ads API interface

hybid.sdk/src/main/java/net/pubnative/lite/sdk/mraid/internal/MRAIDHtmlProcessor.java
- Force MRAID JS script into WebView
=> Inject MRAID JS into WebView

hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/dfp/DFPBannerFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/dfp/DFPInterstitialFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/dfp/DFPMRectFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidBannerFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidInterstitialFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidMRectFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidNativeFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubBannerFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubInterstitialFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubMRectFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubMediationFragment.kt, hybid.demo/src/main/res/layout/fragment_dfp_banner.xml, hybid.demo/src/main/res/layout/fragment_dfp_interstitial.xml, hybid.demo/src/main/res/layout/fragment_dfp_mrect.xml, hybid.demo/src/main/res/layout/fragment_hybid_banner.xml, hybid.demo/src/main/res/layout/fragment_hybid_interstitial.xml, hybid.demo/src/main/res/layout/fragment_hybid_mrect.xml, hybid.demo/src/main/res/layout/fragment_hybid_native.xml, hybid.demo/src/main/res/layout/fragment_mopub_banner.xml, hybid.demo/src/main/res/layout/fragment_mopub_interstitial.xml, hybid.demo/src/main/res/layout/fragment_mopub_mediation.xml, hybid.demo/src/main/res/layout/fragment_mopub_mrect.xml
- Put error messages on all ad screens on a label on the screen for automation purposes.
=> [MA-473] Set error messages on labels on demo app

hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/MainFragment.java, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubFragment.kt, hybid.demo/src/main/res/layout/fragment_main.xml, hybid.demo/src/main/res/layout/fragment_mopub.xml, hybid.demo/src/main/res/values/strings.xml
- Create new Mediation section on the main screen of the SDK demo app
- Add MoPub Mediation to the new section
- Remove MoPub Mediation from the MoPub Pre-Bid section
=> [MA-472] Move MoPub Mediation out of Pre-Bid section

hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/mediation/HyBidMediationBannerCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/mediation/HyBidMediationNativeCustomEvent.java, hybid.demo/src/main/java/net/pubnative/lite/demo/Constants.java, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidNativeFragment.kt, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/NativeAd.java, hybid.sdk/src/test/java/net/pubnative/lite/sdk/models/NativeAdTest.java
- Add Content Info icon and click url to NativeAd
- Create Adapter for Native Ads in MoPub Mediation
=> [MA-476] Native Adapter for MoPub Mediation

hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/AdRequest.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/AdRequestFactory.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/utils/PNApiUrlComposer.java
- Add assets param to the native ad request URL
=> Add assets on native ads url

build.gradle, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/dfp/DFPBannerFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/dfp/DFPInterstitialFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/dfp/DFPMRectFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidBannerFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubBannerFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubInterstitialFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubMRectFragment.kt, hybid.demo/src/main/res/layout/fragment_dfp_banner.xml, hybid.demo/src/main/res/layout/fragment_dfp_interstitial.xml, hybid.demo/src/main/res/layout/fragment_dfp_mrect.xml, hybid.demo/src/main/res/layout/fragment_mopub_banner.xml, hybid.demo/src/main/res/layout/fragment_mopub_interstitial.xml, hybid.demo/src/main/res/layout/fragment_mopub_mrect.xml, hybid.demo/src/main/res/values/strings.xml, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/Ad.java
- Add Impression ID getter on Ad object
- Add label to display impression ID on pre-bid screens
=> Impression ID on ad object

hybid.demo/src/main/java/net/pubnative/lite/demo/HyBidDemoApplication.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/HyBid.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/network/PNHttpRequest.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/utils/Logger.java
- Add set log level to HyBid class
- Set default log level to info
- Log network request URLs and responses if log level is set to debug
=> [MA-474] Log urls and responses of network requests

hybid.demo/src/main/java/net/pubnative/lite/demo/Constants.java, hybid.demo/src/main/java/net/pubnative/lite/demo/HyBidDemoApplication.java, hybid.demo/src/main/java/net/pubnative/lite/demo/SettingConstants.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/managers/SettingsManager.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/models/SettingsModel.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubMediationFragment.kt, hybid.demo/src/main/res/layout/fragment_mopub_mediation.xml, hybid.demo/src/main/res/layout/layout_native_ad.xml, hybid.demo/src/main/res/values/strings.xml
- Render MoPub Native ads using the native adapter on demo app
=> [MA-477] MoPub Native adapter on demo app

hybid.demo/build.gradle, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/dfp/DFPBannerFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/dfp/DFPInterstitialFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/dfp/DFPMRectFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidBannerFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidInterstitialFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidMRectFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidNativeFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubBannerFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubInterstitialFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubMRectFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/util/JsonUtils.kt, hybid.demo/src/main/res/layout/fragment_dfp_banner.xml, hybid.demo/src/main/res/layout/fragment_dfp_interstitial.xml, hybid.demo/src/main/res/layout/fragment_dfp_mrect.xml, hybid.demo/src/main/res/layout/fragment_hybid_banner.xml, hybid.demo/src/main/res/layout/fragment_hybid_interstitial.xml, hybid.demo/src/main/res/layout/fragment_hybid_mrect.xml, hybid.demo/src/main/res/layout/fragment_hybid_native.xml, hybid.demo/src/main/res/layout/fragment_mopub_banner.xml, hybid.demo/src/main/res/layout/fragment_mopub_interstitial.xml, hybid.demo/src/main/res/layout/fragment_mopub_mrect.xml, hybid.demo/src/main/res/values/strings.xml, hybid.sdk/src/main/java/net/pubnative/lite/sdk/api/PNApiClient.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/utils/AdRequestRegistry.java
- Create AdRequestRegistry to save info regarding last request made.
- Add views on the demo app to display debug information related to the request made to pubnative
**This information is not displayed in the MoPub Mediation screen since it will be broken down into independent format screens in the next ticket**
=> [MA-481] Log request url, latency and response in ad pages

hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/dfp/DFPBannerFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/dfp/DFPInterstitialFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/dfp/DFPMRectFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidBannerFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidInterstitialFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidMRectFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidNativeFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubBannerFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubInterstitialFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubMRectFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/util/ClipboardUtils.kt, hybid.demo/src/main/res/layout/fragment_dfp_banner.xml, hybid.demo/src/main/res/layout/fragment_dfp_interstitial.xml, hybid.demo/src/main/res/layout/fragment_dfp_mrect.xml, hybid.demo/src/main/res/layout/fragment_hybid_banner.xml, hybid.demo/src/main/res/layout/fragment_hybid_interstitial.xml, hybid.demo/src/main/res/layout/fragment_hybid_mrect.xml, hybid.demo/src/main/res/layout/fragment_hybid_native.xml, hybid.demo/src/main/res/layout/fragment_mopub_banner.xml, hybid.demo/src/main/res/layout/fragment_mopub_interstitial.xml, hybid.demo/src/main/res/layout/fragment_mopub_mrect.xml
- Make error, request url, latency and response views clickable
- Copy to clipboard content of debug views if they have any text when clicked
=> [MA-481] Add copy to clipboard on debug views

build.gradle, hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/HyBidInterstitialAd.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/views/HyBidBannerAdView.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/views/HyBidMRectAdView.java
- Add null check on Banner, MRect and Interstitial for presenters load method.
=> Null checks on presenters

hybid.sdk/src/main/java/net/pubnative/lite/sdk/banner/presenter/MraidBannerPresenter.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/presenter/MraidInterstitialPresenter.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/mrect/presenter/MraidMRectPresenter.java
- Enable all MRAID native features (calendar, sms, phone, video, save picture) for all ad formats
=> Enable MRAID native features for all formats

hybid.demo/src/main/res/layout/fragment_nav_consent.xml, hybid.sdk/src/main/java/net/pubnative/lite/sdk/tracking/ExceptionHandler.java
- Filter exceptions reported to only the ones coming from the SDK or adapters
=> [MA-499] Report only SDK and Adapter exceptions

hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/navigation/ConsentNavFragment.kt, hybid.demo/src/main/res/layout/fragment_nav_consent.xml, hybid.demo/src/main/res/values/strings.xml, hybid.sdk/src/main/java/net/pubnative/lite/sdk/UserDataManager.java
- Add a method on UserDataManager to determine if data can be collected or not
=> [MA-512] Add method to check if can collect data

hybid.sdk/src/test/java/net/pubnative/lite/sdk/leaderboard/presenter/LeaderboardPresenterDecoratorTest.java, hybid.sdk/src/test/java/net/pubnative/lite/sdk/leaderboard/presenter/LeaderboardPresenterFactoryTest.java, hybid.sdk/src/test/java/net/pubnative/lite/sdk/utils/TestUtil.java, hybid.sdk/src/test/java/net/pubnative/lite/sdk/views/HyBidLeaderboardAdViewTest.java
- Tests for all of the Leaderboard ad new components
=> [AN-21] Leaderboard ad tests

hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/mediation/HyBidMediationLeaderboardCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/mediation/PNLiteMediationLeaderboardCustomEvent.java
- Leaderboard adapter for MoPub mediation
=> [AN-16] Leaderboard MoPub mediation adapter

hybid.adapters.dfp/src/main/java/net/pubnative/lite/adapters/dfp/HyBidDFPLeaderboardCustomEvent.java, hybid.adapters.dfp/src/main/java/net/pubnative/lite/adapters/dfp/PNLiteDFPLeaderboardCustomEvent.java
- Prebid adapter for DFP for the Leaderboard size
=> [AN-18] DFP Prebid adapter for Leaderboard

hybid.sdk/src/main/java/net/pubnative/lite/sdk/utils/IntentHandler.java
- Add New Task flag to activity that open to handle ad clicks
=> Add New Task flag to Application Context click handling

hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/activity/HyBidInterstitialActivity.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/activity/MraidInterstitialActivity.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/mraid/MRAIDBanner.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/mraid/MRAIDView.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/mraid/MRAIDViewCloseLayoutListener.java
- Add CloseLayoutListener to MRAID view
- Assign listener on interstitials to manage HTML close buttons
=> [AN-34] Fix close button on MRAID interstitials

hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/activity/HyBidInterstitialActivity.java
- Trigger interstitial dismissed action when back button pressed on the interstitial activity
=> Fix interstitial dismiss on back button pressed

hybid.sdk/src/main/java/net/pubnative/lite/sdk/vast/VASTPlayer.java
- Remove VAST Model reload from click listener
=> AN-39[]Fix VAST reload on resume issue

.circleci/config.yml, .gitignore, build.gradle, gradle/wrapper/gradle-wrapper.properties, hybid.demo/build.gradle, hybid.demo/src/main/AndroidManifest.xml
- Update Kotlin 1.3.20
- Update Gradle 3.3.0
- Update DFP SDK
=> [AN-44] Update Kotlin, Gradle and Google Libraries

hybid.sdk/src/main/java/net/pubnative/lite/sdk/views/PNAdView.java
- Set PNAdView background color to transparent
=> [AN-49] Set PNAdView background to transparent

build.gradle, hybid.sdk/src/main/java/net/pubnative/lite/sdk/UserDataManager.java
- Fix duplicated user data manager initialisation
=> Remove duplicate user data manager initialisation callback

hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/activity/HyBidInterstitialActivity.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/activity/MraidInterstitialActivity.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/activity/VastInterstitialActivity.java, hybid.sdk/src/main/res/layout/controls.xml, hybid.sdk/src/test/java/net/pubnative/lite/sdk/interstitial/activity/HyBidInterstitialActivityTest.java
- Fix VAST player latency on Android 6 and earlier
- Add content info to VAST interstitial
=> [AN-60] Fix VAST player timer and content info

build.gradle, hybid.sdk/src/main/java/net/pubnative/lite/sdk/mraid/MRAIDView.java
- Add flag to make MRAID view loaded callback happen only once.
=> [AN-62] Avoid MRAID loaded callback from repeating

hybid.sdk/src/main/java/net/pubnative/lite/sdk/DeviceInfo.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/AdvertisingInfo.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/utils/HyBidAdvertisingId.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/utils/PNAsyncUtils.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/utils/reflection/MethodBuilderFactory.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/utils/reflection/ReflectionUtils.java
- Change the Fetch advertising id process for an AsyncTask
- Create an executor to run the fetch GAID task with higher priority
=> [AN-67] Improve speed of fetching GAID on SDK init

hybid.demo/build.gradle, hybid.sdk/src/main/java/net/pubnative/lite/sdk/api/PNApiClient.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/network/PNHttpClient.java
- Create new Http client that uses AsyncTask
- Replace HttpRequest in PNApiClient for the new Http client.
=> [AN-68] Http Client with AsyncTask

hybid.sdk/src/main/java/net/pubnative/lite/sdk/network/PNHttpClient.java
- Remove the response code log from HTTP Client
- Close input stream after reading content of the HTTP response
=> Close input stream from HTTP Client

hybid.demo/src/main/java/net/pubnative/lite/demo/ui/adapters/MarkupAdapter.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/markup/MarkupFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/viewholders/MarkupLeaderboardViewHolder.kt, hybid.demo/src/main/res/layout/fragment_markup.xml, hybid.demo/src/main/res/layout/item_markup_leaderboard.xml
- Add leaderboard to custom markup screen
- Change layout of radio buttons in custom markup screen to fit new leaderboard option
=> [OMA-545] Leaderboard support to custom markup

build.gradle, hybid.adapters.dfp/build.gradle, hybid.adapters.mopub/build.gradle, hybid.demo/build.gradle
- Support MoPub SDK 5.8.0
- Update Android utils libraries
=> [ OMA-544] Support for MoPub SDK 5.8.0

hybid.sdk/src/main/java/net/pubnative/lite/sdk/DeviceInfo.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/api/RequestManager.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/AdRequestFactory.java, hybid.sdk/src/test/java/net/pubnative/lite/sdk/models/AdRequestFactoryTest.java
- Fetch advertising id on SDK requests if it's not present when an ad request is made.
=> [OMA-547] First request improvements

hybid.adapters.admob/build/generated/source/buildConfig/debug/net/pubnative/lite/adapters/admob/BuildConfig.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/HyBidInterstitialAd.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/presenter/InterstitialPresenterFactory.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/presenter/MraidInterstitialPresenter.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/presenter/VastInterstitialPresenter.java
- Change parameter on HyBidInterstitialAd constructor to Context
- Change parameter on InterstitialFactory constructor to Context
- Change parameter on Interstitial presenters constructor to Context
=> Change interstitial constructor to Context

hybid.adapters.mopub/build.gradle, hybid.demo/build.gradle
=> [OMA-566] Update support for MoPub 5.9.0

hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidMRectFragment.kt, hybid.demo/src/main/res/layout/activity_tab.xml, hybid.demo/src/main/res/layout/fragment_admob_banner.xml, hybid.demo/src/main/res/layout/fragment_admob_interstitial.xml, hybid.demo/src/main/res/layout/fragment_admob_leaderboard.xml, hybid.demo/src/main/res/layout/fragment_admob_mrect.xml, hybid.demo/src/main/res/layout/fragment_debug.xml, hybid.demo/src/main/res/layout/fragment_dfp_banner.xml, hybid.demo/src/main/res/layout/fragment_dfp_interstitial.xml, hybid.demo/src/main/res/layout/fragment_dfp_leaderboard.xml, hybid.demo/src/main/res/layout/fragment_dfp_mrect.xml, hybid.demo/src/main/res/layout/fragment_hybid_banner.xml, hybid.demo/src/main/res/layout/fragment_hybid_interstitial.xml, hybid.demo/src/main/res/layout/fragment_hybid_leaderboard.xml, hybid.demo/src/main/res/layout/fragment_hybid_mrect.xml, hybid.demo/src/main/res/layout/fragment_hybid_native.xml, hybid.demo/src/main/res/layout/fragment_markup.xml, hybid.demo/src/main/res/layout/fragment_mopub_banner.xml, hybid.demo/src/main/res/layout/fragment_mopub_interstitial.xml, hybid.demo/src/main/res/layout/fragment_mopub_leaderboard.xml, hybid.demo/src/main/res/layout/fragment_mopub_mrect.xml, hybid.demo/src/main/res/layout/fragment_mopub_native.xml, hybid.demo/src/main/res/layout/fragment_nav_consent.xml, hybid.demo/src/main/res/values/strings.xml, hybid.sdk/src/main/java/net/pubnative/lite/sdk/mraid/MRAIDView.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/tracking/EventReceiver.java
- Remove unused IDs in resource files
- Remove old methods
=> [OMA-569] Size cleanup

hybid.adapters.admob/src/main/java/net/pubnative/hybid/adapters/admob/mediation/HyBidMediationBannerCustomEvent.java, hybid.adapters.admob/src/main/java/net/pubnative/hybid/adapters/admob/mediation/HyBidMediationInterstitialCustomEvent.java, hybid.adapters.admob/src/main/java/net/pubnative/hybid/adapters/admob/mediation/HyBidMediationLeaderboardCustomEvent.java, hybid.adapters.admob/src/main/java/net/pubnative/hybid/adapters/admob/mediation/HyBidMediationMRectCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/mediation/HyBidMediationBannerCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/mediation/HyBidMediationInterstitialCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/mediation/HyBidMediationLeaderboardCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/mediation/HyBidMediationMRectCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/mediation/HyBidMediationNativeCustomEvent.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/api/RequestManager.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/HyBidInterstitialAd.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/AdRequest.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/AdRequestFactory.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/IntegrationType.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/nativead/HyBidNativeAdRequest.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/utils/PNApiUrlComposer.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/views/PNAdView.java, hybid.sdk/src/test/java/net/pubnative/lite/sdk/models/AdRequestFactoryTest.java
- Add display manager field to the Api request
- Set display manager value on each integration type
=> Display manager on API v3 request

build.gradle, hybid.adapters.admob/build/generated/source/buildConfig/debug/net/pubnative/lite/adapters/admob/BuildConfig.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/views/PNWebView.java
- Fix resource loading issue on WebView for Android 5
=> Fix Android 5 webview issues

build.gradle, hybid.adapters.mopub/build.gradle, hybid.demo/build.gradle
- Update MoPub SDK to 5.10.0
- Update Gradle plugin to 3.5.2
=> [OMA-584] Update MoPub SDK to 5.10.0

hybid.adapters.admob/build/generated/source/buildConfig/debug/net/pubnative/lite/adapters/admob/BuildConfig.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/api/PNApiClient.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/network/PNHttpClient.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/network/PendingRequest.java
- Retry failed impression/click beacon confirmations
=> [OMA-587] Retry failed confirmation beacons

.circleci/config.yml, build.gradle, fastlane/Fastfile, hybid.demo/build.gradle, hybid.demo/src/main/java/net/pubnative/lite/demo/HyBidDemoApplication.java
- Remove Fabric support for HyBid demo app
- Add Firebase App Distribution to gradle
- Publish demo app on from CircleCI to Firebase
=> [OMA-602] Publish demo app on Firebase

hybid.sdk/src/main/java/net/pubnative/lite/sdk/UserDataManager.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/consent/UserConsentActivity.java
- Change CMP consent dialog url
- Change redirection urls for accepting or denying consent
=> [OMA-621] Update CMP consent dialog URLs

build.gradle, hybid.adapters.admob/build/generated/source/buildConfig/debug/net/pubnative/lite/adapters/admob/BuildConfig.java, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/adapters/InFeedAdapter.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidBannerFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidInterstitialFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidLeaderboardFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidMRectFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidNativeFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubBannerFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubInterstitialFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubLeaderboardFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubMRectFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/listeners/InFeedAdListener.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/viewholders/HyBidMRectViewHolder.kt, hybid.demo/src/main/res/layout/fragment_hybid_banner.xml, hybid.demo/src/main/res/layout/fragment_hybid_interstitial.xml, hybid.demo/src/main/res/layout/fragment_hybid_leaderboard.xml, hybid.demo/src/main/res/layout/fragment_hybid_mrect.xml, hybid.demo/src/main/res/layout/fragment_hybid_native.xml, hybid.demo/src/main/res/layout/fragment_mopub_banner.xml, hybid.demo/src/main/res/layout/fragment_mopub_interstitial.xml, hybid.demo/src/main/res/layout/fragment_mopub_leaderboard.xml, hybid.demo/src/main/res/layout/fragment_mopub_mrect.xml, hybid.demo/src/main/res/values/strings.xml, hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/HyBidInterstitialAd.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/Ad.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/AdRequestFactory.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/NativeAd.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/views/PNAdView.java, hybid.sdk/src/test/java/net/pubnative/lite/sdk/models/AdRequestFactoryTest.java
- Expose the creative ID via a function in the Ad object
- Replace impression ID by creative ID in the demo app
=> [OMA-645] Expose creative ID to publishers

hybid.demo/src/main/AndroidManifest.xml, hybid.demo/src/main/java/net/pubnative/lite/demo/HyBidDemoApplication.java, hybid.demo/src/main/java/net/pubnative/lite/demo/SettingConstants.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/managers/SettingsManager.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/models/SettingsModel.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/activities/config/BrowserPriorityActivity.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/adapters/PackageNameAdapter.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/config/BrowserPriorityFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/config/HyBidSettingsFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/listeners/PackageNameClickListener.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/viewholders/PackageNameViewHolder.kt, hybid.demo/src/main/res/layout/activity_browser_priorities.xml, hybid.demo/src/main/res/layout/fragment_browser_priorities.xml, hybid.demo/src/main/res/layout/fragment_hybid_settings.xml, hybid.demo/src/main/res/layout/item_package_name.xml, hybid.demo/src/main/res/values/strings.xml, hybid.sdk/src/main/java/net/pubnative/lite/sdk/HyBid.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/browser/BrowserManager.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/utils/IntentHandler.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/utils/UrlHandler.java
- Create BrowserManager to handle preferences of browser to handle ad click
- Add screen on demo app to set browser package names
=> [OMA-677] Set preferred browsers to handle ad click

build.gradle, hybid.sdk/src/main/java/net/pubnative/lite/sdk/utils/CountryUtils.java
- Update CountryUtils with country codes.
=> UserDataManager consent updates

hybid.sdk/src/main/java/net/pubnative/lite/sdk/mraid/MRAIDView.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/viewability/HyBidViewabilityAdSession.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/viewability/HyBidViewabilityNativeAdSession.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/viewability/HyBidViewabilityNativeVideoAdSession.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/viewability/HyBidViewabilityWebAdSession.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/BaseVideoAd.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/BaseVideoAdInternal.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/VideoAd.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/VideoAdController.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/VideoAdControllerVast.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/VideoAdControllerVpaid.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/helpers/EventTracker.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/models/TrackingEvent.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/models/vast/AdVerifications.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/models/vast/Extension.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/models/vast/InLine.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/models/vast/JavaScriptResource.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/models/vast/VastAdSource.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/models/vast/Verification.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/models/vast/VerificationParameters.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/models/vast/Wrapper.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/response/AdParams.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/response/VastProcessor.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/vast/ViewControllerVast.java
- Reorganise the OM Ad sessions classes
- Add support for native video viewability tracking on the VAST player
=> [OMA-714] OM SDK support for VAST player

build.gradle, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/VpaidConstants.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/response/VastProcessor.java
- Add some null checks and change some conditions for VAST Wrapper support
- Increase the timeout for loading VPAID ads to 15 seconds
- Fix VPAID html ad rendering
=> Fix VAST wrapper

hybid.sdk/src/main/java/net/pubnative/lite/sdk/UserDataManager.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/activity/CenteredMraidInterstitialActivity.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/activity/MraidInterstitialActivity.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/AdRequestFactory.java, hybid.sdk/src/test/java/net/pubnative/lite/sdk/models/AdRequestFactoryTest.java
- Add method to stop OM session on centered interstitial activity
- Small fix on CCPA opt out check
=> Stop ad session on centered interstitial destroy method

hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/HyBidMoPubBannerCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/HyBidMoPubInterstitialCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/HyBidMoPubLeaderboardCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/HyBidMoPubMRectCustomEvent.java
- Refactor header bidding adapters for MoPub 5.13
=> [OMA-747] Update header bidding adapters for MoPub

hybid.sdk/src/main/java/net/pubnative/lite/sdk/api/PNApiClient.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/AdData.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/utils/AdTracker.java
- Add confirmation for JS beacons on Android SDK
=> [OMA-740] Confirm JS beacons

hybid.sdk/src/main/java/net/pubnative/lite/sdk/HyBid.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/api/RequestManager.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/location/HyBidLocationManager.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/AdRequestFactory.java
- Add null check for Device Info on the AdRequestFactory
- Create HyBidLocationManager only if the Location Service is available
=> Fix Device info and location manager corner case crashes

build.gradle, hybid.demo/src/main/java/net/pubnative/lite/demo/HyBidDemoApplication.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/HyBid.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/api/RequestManager.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/location/HyBidLocationManager.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/AdRequestFactory.java
- Add checks for available location manager and device info
- Add flag to disable location updates
=> Flag to disable location updates

hybid.demo/src/main/java/net/pubnative/lite/demo/util/JsonUtils.kt
- Check for valid JSON on the demo app debug fragment
=> [OMA-754] Fix demo app JSON parser

build.gradle, hybid.sdk/src/main/java/net/pubnative/lite/sdk/viewability/ViewabilityManager.java
- Make the block that initialises OM SDK run on the main thread.
=> Force OM SDK to initialise in the main thread

hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/Ad.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/mraid/MRAIDView.java
- Add check to catch Verve expand redirect and add it to the standard MRAID expand.
=> [OMA-777] Support Verve expandable creatives on HyBid SDK

hybid.sdk/src/main/java/net/pubnative/lite/sdk/viewability/HyBidViewabilityNativeVideoAdSession.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/VideoAdControllerVpaid.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/vast/ViewControllerVast.java
- Trigger video click event on OM SDK
=> [OMA-787] Video click event tracking for OM SDK

build.gradle, hybid.demo/build.gradle, hybid.demo/src/main/AndroidManifest.xml, hybid.demo/src/main/java/net/pubnative/lite/demo/Constants.java, hybid.demo/src/main/java/net/pubnative/lite/demo/HyBidDemoApplication.java, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/activities/consent/GoogleCMPActivity.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/activities/consent/OguryCMPActivity.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/activities/consent/PNCMPActivity.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/consent/ConsentStringsFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/consent/GoogleCMPFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/consent/OguryCMPFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/consent/PNCMPFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/navigation/ConsentNavFragment.kt, hybid.demo/src/main/res/layout/activity_google_cmp.xml, hybid.demo/src/main/res/layout/activity_ogury_cmp.xml, hybid.demo/src/main/res/layout/activity_pn_cmp.xml, hybid.demo/src/main/res/layout/fragment_consent_strings.xml, hybid.demo/src/main/res/layout/fragment_google_cmp.xml, hybid.demo/src/main/res/layout/fragment_nav_consent.xml, hybid.demo/src/main/res/layout/fragment_ogury_cmp.xml, hybid.demo/src/main/res/layout/fragment_pn_cmp.xml, hybid.demo/src/main/res/values/strings.xml, hybid.sdk/src/main/java/net/pubnative/lite/sdk/UserDataManager.java
- Add Ogury CMP SDK to the HyBid demo app
- Create Ogury CMP screen for setting and checking the consent
=> [OMA-798] Ogury CMP on demo app

hybid.demo/build.gradle, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/consent/GoogleCMPFragment.kt, hybid.demo/src/main/res/layout/fragment_google_cmp.xml, hybid.demo/src/main/res/layout/fragment_nav_consent.xml, hybid.demo/src/main/res/values/strings.xml
- Add TrustedChoices CMP to demo app
- Create fragment for new CMP testing
=> [OMA-802] Integrate Trusted Choices CMP

build.gradle, hybid.adapters.admob/build.gradle, hybid.adapters.dfp/build.gradle, hybid.adapters.mopub/build.gradle, hybid.demo/build.gradle, hybid.demo/src/main/java/net/pubnative/lite/demo/managers/SettingsManager.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/models/SettingsModel.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/util/ClipboardUtils.kt, hybid.sdk/build.gradle
- Update build Android SDK for all modules to API 30
- Fix clipboard utils on demo app for new API
=> Android 11 compatibility

build.gradle, hybid.sdk/src/main/java/net/pubnative/lite/sdk/location/HyBidLocationManager.java
- Add null check for OS location manager on the HyBidLocationManager class
=> HyBidLocationManager fix

hybid.demo/src/main/AndroidManifest.xml, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/activities/signaldata/SignalDataActivity.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/adapters/SignalDataAdapter.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidInterstitialFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/markup/MarkupFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/navigation/SettingsNavFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/signaldata/SignalDataFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/vast/VastTagRequestFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/viewholders/MarkupBannerViewHolder.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/viewholders/MarkupLeaderboardViewHolder.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/viewholders/SignalDataBannerViewHolder.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/viewholders/SignalDataLeaderboardViewHolder.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/viewholders/SignalDataMRectViewHolder.kt, hybid.demo/src/main/res/layout/activity_signal_data.xml, hybid.demo/src/main/res/layout/fragment_nav_settings.xml, hybid.demo/src/main/res/layout/fragment_signal_data.xml, hybid.demo/src/main/res/values/strings.xml, hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/HyBidInterstitialAd.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/activity/HyBidInterstitialActivity.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/activity/VastInterstitialActivity.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/presenter/InterstitialPresenterFactory.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/presenter/VastInterstitialPresenter.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/views/HyBidAdView.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/views/HyBidBannerAdView.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/views/HyBidLeaderboardAdView.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/views/HyBidMRectAdView.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/VideoAdControllerVast.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/response/AdParams.java, hybid.sdk/src/test/java/net/pubnative/lite/sdk/interstitial/presenter/InterstitialPresenterFactoryTest.java
- Move custom markup rendering to different method
- Use JSON signal data on renderAd & prepareAd methods for MaxAds custom integration
=> [OMA-807] Use signal data for rendering custom MaxAds response

build.gradle, hybid.adapters.mopub/build.gradle, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/mediation/HyBidMediationBannerCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/mediation/HyBidMediationInterstitialCustomEvent.java, hybid.demo/build.gradle
- Update MoPub adapters to 5.14
- Fix impression tracker on new MoPub adapters
=> [OMA-811] MoPub 5.14 adapter fixes

hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/vast/VastTagRequestFragment.kt, hybid.demo/src/main/res/layout/fragment_vast_tag.xml, hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/HyBidInterstitialAd.java
Added feature to load vast tags directly for Interstitial
=> HyBidX - Feature to load vast tags directly

build.gradle, hybid.adapters.admob/src/main/java/net/pubnative/hybid/adapters/admob/mediation/HyBidMediationBannerCustomEvent.java
- Change HyBidBannerAdView for generic HyBidAdView in Admob banner adapters
=> Fix Admob MRect adapter Request Manager size
