pubnative/pubnative-hybid-android-sdk

build.gradle, hybid.adapters.mopub/build.gradle, hybid.demo/build.gradle
- Update MoPub SDK version to 5.2.0 in Adapters and Demo
- Bump HyBid SDK version to 0.2.1
=> [MA-475] Update MoPub SDK to 5.2.0

hybid.demo/build.gradle, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/adapters/KeywordAdapter.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/adapters/ZoneIdAdapter.kt
- Update Android AppCompat and Design libraries to 27.1.1
- Update ConstraintLayout library to 1.1.2
- Fix issues with RecyclerView adapters in Kotlin after updating the libs
=> Update support libraries in demo app to 27.1.1

hybid.demo/src/main/AndroidManifest.xml, hybid.demo/src/main/res/xml/network_security_config.xml
- Bypass SSL security so Charles Proxy can be used in devices with Android 7 or higher.
=> [MA-479] Bypass SSL security for demo app

hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/config/MoPubSettingsFragment.kt, hybid.demo/src/main/res/layout/fragment_mopub_settings.xml, hybid.demo/src/main/res/values/strings.xml
- Add fields to edit the MoPub Mediation ad units on the demo app
=> Add fields on MoPub settings for mediation ad units

hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/Ad.java
- Return default minimum eCPM (0.01) if the API doesn't return the POINTS meta field
=> Fix eCPM keyword generation

build.gradle, hybid.sdk/src/main/java/net/pubnative/lite/sdk/location/HyBidLocationManager.java
- Check if GPS and network provider exist before initialising the LocationManager.
- Add provider checks before every location update.
=> Check for missing location providers on HyBidLocationManager

build.gradle, gradle/wrapper/gradle-wrapper.properties, hybid.adapters.mopub/build.gradle, hybid.demo/build.gradle, hybid.sdk/build.gradle
- MoPub 5.3.0
- Kotlin 1.2.61
- Kotlin JRE 7 runtime
=> [MA-497] Support for MoPub 5.3.0

hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/dfp/DFPBannerFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/dfp/DFPInterstitialFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/dfp/DFPMRectFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubBannerFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubInterstitialFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubMRectFragment.kt, hybid.sdk/src/main/java/net/pubnative/lite/sdk/utils/PrebidUtils.java
- Remove pn: true and zone_id keywords from MoPub request after probed
- Update demo app with methods without zone id.
=> [MA-503] Remove extra keywords from PreBid

hybid.sdk/src/main/java/net/pubnative/lite/sdk/UserDataManager.java
- Add gaid to the cached values when consent is given or denied
- Compare current gaid with the stored one to know if the given consent if for that ID.
=> [MA-509] Check for GAID on consent cache

hybid.sdk/src/main/java/net/pubnative/lite/sdk/api/LeaderboardRequestManager.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/leaderboard/presenter/LeaderboardPresenter.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/leaderboard/presenter/LeaderboardPresenterDecorator.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/leaderboard/presenter/LeaderboardPresenterFactory.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/leaderboard/presenter/MraidLeaderboardPresenter.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/views/HyBidLeaderboardAdView.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/views/PNLeaderboardAdView.java
- Support for Leaderboard size banners (728x90)
- HyBidLeaderboardAdView as a self contained view for the leaderboard ads
=> [AN-15] Leaderboard support for Standalone integration

hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/HyBidMoPubInterstitialCustomEvent.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/AdCache.java
- Add method **inspect** in the AdCache to check ads without removing.
- Replace **remove** method from AdCache by **inspect** in prebid interstitial adapter
=> [AN-31] Fix ad cache for Prebid interstitial

hybid.adapters.mopub/build.gradle, hybid.demo/build.gradle, hybid.demo/src/main/java/net/pubnative/lite/demo/managers/MoPubManager.java
- Update MoPub SDK support to 5.5.0
- Set MoPub log levels to DEBUG, therefore seeing all actions triggered but the SDK.
=> [AN-48] Update MoPub SDK 5.5.0

build.gradle, hybid.sdk/src/main/java/net/pubnative/lite/sdk/mraid/MRAIDView.java
- Add flag to prevent ad choices to be added twice in case that the HTML view does an internal load of a different page.
=> Fix duplicated ad choices insertion

build.gradle, gradle/wrapper/gradle-wrapper.properties, hybid.sdk/build.gradle
- Update Gradle plugin to 3.4.0
- Update Kotlin to 1.3.30
=> Update Gradle for new Android Studio 3.4.0

.circleci/config.yml, fastlane/Fastfile
- Add lane for lint checks on the CircleCI build
- Make build fail if code conventions are not respected
=> [AN-78] Check Lint on CircleCI build

hybid.sdk/src/main/java/net/pubnative/lite/sdk/views/PNWebView.java
- Enable WebView debugging in Chrome if debuggable flag is set on the Android Manifest
=> Enable WebView debugging in Chrome

build.gradle, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidBannerFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidInterstitialFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidLeaderboardFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidMRectFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/hybid/HyBidNativeFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubBannerFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubInterstitialFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubLeaderboardFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubMRectFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/listeners/InFeedAdListener.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/viewholders/HyBidMRectViewHolder.kt, hybid.demo/src/main/res/layout/fragment_hybid_banner.xml, hybid.demo/src/main/res/layout/fragment_hybid_interstitial.xml, hybid.demo/src/main/res/layout/fragment_hybid_leaderboard.xml, hybid.demo/src/main/res/layout/fragment_hybid_mrect.xml, hybid.demo/src/main/res/layout/fragment_hybid_native.xml, hybid.demo/src/main/res/layout/fragment_mopub_banner.xml, hybid.demo/src/main/res/layout/fragment_mopub_interstitial.xml, hybid.demo/src/main/res/layout/fragment_mopub_leaderboard.xml, hybid.demo/src/main/res/layout/fragment_mopub_mrect.xml, hybid.demo/src/main/res/values/strings.xml, hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/HyBidInterstitialAd.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/NativeAd.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/views/PNAdView.java
- Add function to get Impression ID from standalone ads
- Add field on standalone and header bidding screens on the demo app to display the impression ID
=> [OMA-536] Impression ID on standalone ad view

hybid.adapters.admob/build.gradle, hybid.adapters.dfp/build.gradle, hybid.adapters.mopub/build.gradle, hybid.demo/build.gradle, hybid.sdk/build.gradle
- Raise minimum api version required for HyBid SDK to 19
- Update MoPub SDK to 5.11.0
=> [OMA-646] MoPub SDK 5.11.0 support

hybid.sdk/src/main/java/net/pubnative/lite/sdk/utils/UrlHandler.java
- Add redirect=false as a param in the click url of creatives. It's an anti fraud measure.
=> Add redirect=false as param in the click url

build.gradle, hybid.adapters.admob/build.gradle, hybid.adapters.dfp/build.gradle, hybid.adapters.mopub/build.gradle, hybid.demo/build.gradle, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubBannerFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubLeaderboardFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubMRectFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubMediationBannerFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubMediationLeaderboardFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubMediationMRectFragment.kt
- Bump HyBid version to 0.9.0
- Update MoPub SDK to 5.12.0
- Update Admob SDK to 19.1.0
- Prepare for release without crash tracker
=> Update MoPub, Admob and bump HyBid version to 0.9.0

build.gradle, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/response/VastProcessor.java
- Add condition to declare no fill for VAST videos. In some cases there's an ad but no status flag.
=> Fix condition to declare no fill on Vast parser

build.gradle, hybid.demo/build.gradle, hybid.sdk/src/main/AndroidManifest.xml, hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/activity/CenteredMraidInterstitialActivity.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/interstitial/presenter/MraidInterstitialPresenter.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/Ad.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/AdData.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/utils/ViewUtils.java
- Add centered interstitial activity to HyBid
- Add methods to get asset size on APIv3 ad model
- Use sizes to determine if fullscreen or framed interstitial should be used
=> [OMA-739] Use APIv3 asset size for interstitial framing

hybid.adapters.mopub/src/main/java/com/mopub/mobileads/HyBidAdapterConfiguration.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/HyBidMoPubBannerCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/HyBidMoPubInterstitialCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/HyBidMoPubLeaderboardCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/HyBidMoPubMRectCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/mediation/HyBidMediationBannerCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/mediation/HyBidMediationInterstitialCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/mediation/HyBidMediationLeaderboardCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/mediation/HyBidMediationMRectCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/mediation/HyBidMediationNativeCustomEvent.java, hybid.demo/build.gradle, hybid.demo/src/main/java/net/pubnative/lite/demo/HyBidDemoApplication.java, hybid.demo/src/main/java/net/pubnative/lite/demo/managers/MoPubManager.java, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/config/MoPubSettingsFragment.kt
- Add MoPub event logging to adapters
- Add initialisation adapter for HyBid SDK
=> [OMA-750] Add MoPub loggin and initialisation adapter to 5.13 update

hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/HyBidMoPubBannerCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/HyBidMoPubInterstitialCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/HyBidMoPubLeaderboardCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/HyBidMoPubMRectCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/PNLiteMoPubBannerCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/PNLiteMoPubInterstitialCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/PNLiteMoPubLeaderboardCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/PNLiteMoPubMRectCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/mediation/PNLiteMediationBannerCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/mediation/PNLiteMediationInterstitialCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/mediation/PNLiteMediationLeaderboardCustomEvent.java, hybid.adapters.mopub/src/main/java/net/pubnative/lite/adapters/mopub/mediation/PNLiteMediationMRectCustomEvent.java, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/dfp/DFPBannerFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/dfp/DFPInterstitialFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/dfp/DFPLeaderboardFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/dfp/DFPMRectFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubBannerFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubInterstitialFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubLeaderboardFragment.kt, hybid.demo/src/main/java/net/pubnative/lite/demo/ui/fragments/mopub/MoPubMRectFragment.kt, hybid.sdk/src/main/java/net/pubnative/lite/sdk/utils/HeaderBiddingUtils.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/utils/PrebidUtils.java
- Add back old header bidding adapters for backwards compatibility
- Refactor method names on HeaderBiddingUtils class
=> [OMA-791] MoPub header bidding adapters backwards compatibility

build.gradle, gradle/wrapper/gradle-wrapper.properties, hybid.demo/build.gradle, hybid.sdk/build.gradle, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/AdRequestFactory.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/viewability/ViewabilityManager.java, hybid.sdk/src/test/java/net/pubnative/lite/sdk/models/AdRequestFactoryTest.java
- Update grade android plugin to version 4.1
- Update cobertura grade plugin to one compatible with the new gradle
- Create SDK_VERSION variable on the build.gradle file to read the reference from the Java code
=> [OMA-814] Update gradle android plugin 4.1

hybid.sdk/src/main/java/net/pubnative/lite/sdk/viewability/HyBidViewabilityNativeVideoAdSession.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/vpaid/response/VastProcessor.java
- Stop from notifying volume changes to OM SDK if the ad session is over
- Null check for StaticResource object for companion ads
=> [OMA-810] Check for session finished before reporting volume change

build.gradle, hybid.adapters.admob/build.gradle, hybid.adapters.dfp/build.gradle, hybid.demo/build.gradle, hybid.sdk/src/main/java/net/pubnative/lite/sdk/UserDataManager.java, hybid.sdk/src/main/java/net/pubnative/lite/sdk/models/AdRequestFactory.java
- Create a method on user data manager to check if consent has been explicitly denied
- Remove user info params from ad request if the consent is explicitly denied.
=> [OMA-863] Clean up user data with negative consent
